### ISSUE TITLE
What is the use of DataFrameParser in example notebook?

### ISSUE THREAD

**Issue by omaralvarez** [UCLA-Trustworthy-AI-Lab/AutoDiffusion#1]
I was trying to replicate your results and taking a look at the example notebook, the following variable is only used at the beginning of the notebook and never used again: 

``` python
parser = DataFrameParser().fit(self.data, self.threshold)
``` 

Is that correct or it is just a mistake and it serves no purpose?

**Comment by namjoonsuh** [comment]
Hi Omar. 
Thanks for your interest in our work. 

DataFrameParser() is for pre-processing input data described in our paper. 
You can ignore the line in the example notebook. 
DataFrameParser plays its role in the autoencoder.py file. 

Feel free to let us know if you have any further questions.

**Comment by omaralvarez** [comment]
Got it! Thanks a lot, it was what I was thinking, but just wanted to confirm. No other questions on my part, the rest of the code worked well.
